/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kenjishioya.kubernetes_grpc;

import com.kenjishioya.kubernetes_grpc.grpc_server.AppGrpcServer;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }
    public static void main(String[] args) {
        AppGrpcServer server = new AppGrpcServer();
        try {
            server.serve();
        } catch (Exception e) {
            System.out.println("Error occured");
            System.exit(1);
        }
    }
}
