apiVersion: v1
kind: Service
metadata:
  name: kubernetes-grpc-go
  labels:
    app: kubernetes-grpc
    component: go
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    component: go